services:
    icamys_barcode.generator:
        class: SGK\BarcodeBundle\Generator\Generator

    icamys_barcode.twig.extension:
        class: SGK\BarcodeBundle\Twig\Extensions\Barcode
        arguments:
            - '@icamys_barcode.generator'
        tags:
            - { name: twig.extension }
